import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    if (!process.env.GOOGLE_AI_KEY) {
      return NextResponse.json(
        { error: 'Google AI API key not configured' },
        { status: 500 }
      )
    }

    const { imageData } = await request.json()
    if (!imageData) {
      return NextResponse.json(
        { error: 'No image provided' },
        { status: 400 }
      )
    }

    const base64Data = imageData.includes(',')
      ? imageData.split(',')[1]
      : imageData
    const mimeType = imageData.includes(',')
      ? imageData.split(',')[0].split(':')[1].split(';')[0]
      : 'image/jpeg'

    const prompt = `Enhance the provided restaurant food photo for a premium menu presentation. Keep the composition intact but boost clarity, lighting, and saturation so it looks like a professional plate shot in Erbil. Return the improved image only.`

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${process.env.GOOGLE_AI_KEY}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  inlineData: {
                    mimeType,
                    data: base64Data,
                  },
                },
              ],
            },
            {
              parts: [
                {
                  text: prompt,
                },
              ],
            },
          ],
          generationConfig: {
            responseModalities: ['image'],
            temperature: 0.4,
            topK: 40,
            topP: 0.9,
          },
        }),
      }
    )

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Gemini enhancement error:', errorText)
      throw new Error(`Gemini API error: ${response.status}`)
    }

    const data = await response.json()
    const candidates = data.candidates
    if (!candidates || candidates.length === 0) {
      throw new Error('No image generated by Gemini')
    }

    const parts = candidates[0]?.content?.parts || []
    let imageBase64: string | null = null
    let imageMimeType = 'image/png'

    for (const part of parts) {
      if (part.inlineData?.mimeType?.startsWith('image/')) {
        imageBase64 = part.inlineData.data
        imageMimeType = part.inlineData.mimeType
        break
      }
    }

    if (!imageBase64) {
      throw new Error('Gemini did not return image data')
    }

    return NextResponse.json({
      success: true,
      imageUrl: `data:${imageMimeType};base64,${imageBase64}`,
    })
  } catch (error) {
    console.error('Error enhancing image:', error)
    return NextResponse.json(
      {
        error: 'Failed to enhance image',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    )
  }
}
