import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import {
  ImageOrientation,
  ImageSizePreset,
  imageOrientationPrompts,
  imageSizePrompts,
} from '@/lib/image-format'
import { enforceImageDimensions } from '@/lib/image-processor'

export async function POST(request: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const {
      prompt,
      itemName,
      description,
      category,
      orientation = 'landscape',
      sizePreset = 'medium',
    }: {
      prompt?: string | null
      itemName?: string
      description?: string
      category?: string
      orientation?: ImageOrientation
      sizePreset?: ImageSizePreset
    } = await request.json()

    if (!process.env.GOOGLE_AI_KEY) {
      return NextResponse.json(
        { error: 'Google AI API key not configured' },
        { status: 500 }
      )
    }

    // Build orientation / size hints and merge with provided prompt
    const orientationHint = imageOrientationPrompts[orientation] ?? ''
    const sizeHint = imageSizePrompts[sizePreset] ?? ''

    const basePrompt =
      !prompt || !prompt.trim()
        ? `Professional food photography of ${itemName}${
            category ? ` (${category})` : ''
          }${description ? `, ${description}` : ''}. IMPORTANT: The dish must be fully visible and centered in the frame - do not crop or cut off any part of the food. Show the complete dish from a slightly elevated angle. High-quality, appetizing presentation on a clean plate with beautiful lighting, garnish, and styling. Leave adequate margin around the food. Restaurant menu quality, photorealistic, full dish visible with nothing cut off.`
        : prompt.trim()

    const hintParts = [orientationHint, sizeHint].filter(Boolean)
    const imagePrompt = hintParts.length
      ? `${basePrompt} ${hintParts.join(' ')}`
      : basePrompt

    console.log('Generating image with Gemini 2.5 Flash Image:', imagePrompt)

    // Use Gemini 2.5 Flash Image API directly
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${process.env.GOOGLE_AI_KEY}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: imagePrompt,
                },
              ],
            },
          ],
          generationConfig: {
            responseModalities: ['image'],
            temperature: 1,
            topK: 40,
            topP: 0.95,
          },
        }),
      }
    )

    if (!response.ok) {
      const errorText = await response.text()
      console.error('Gemini API error:', errorText)
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`)
    }

    const data = await response.json()
    console.log('Full Gemini response:', JSON.stringify(data, null, 2))

    // Extract the image data from the response
    const candidates = data.candidates
    if (!candidates || candidates.length === 0) {
      console.error('No candidates in response:', JSON.stringify(data, null, 2))
      return NextResponse.json(
        { error: 'No image generated by Gemini', details: JSON.stringify(data) },
        { status: 500 }
      )
    }

    if (!candidates[0].content || !candidates[0].content.parts) {
      console.error('Invalid candidate structure:', JSON.stringify(candidates[0], null, 2))
      return NextResponse.json(
        { error: 'Invalid response structure from Gemini', details: JSON.stringify(candidates[0]) },
        { status: 500 }
      )
    }

    const parts = candidates[0].content.parts
    let imageBase64: string | null = null
    let imageMimeType: string = 'image/png'

    // Find the image in the response parts
    for (const part of parts) {
      if (part.inlineData && part.inlineData.mimeType?.startsWith('image/')) {
        imageBase64 = part.inlineData.data
        imageMimeType = part.inlineData.mimeType
        break
      }
    }

    if (!imageBase64) {
      // If no inline data, check if there's a text response with error
      const textResponse = parts.find((p: any) => p.text)?.text
      console.error('No image data found. Response:', JSON.stringify(parts, null, 2))
      return NextResponse.json(
        {
          error: 'No image data found in response',
          details: textResponse || 'Gemini did not return image data'
        },
        { status: 500 }
      )
    }

    // Return as data URL (same as marketing-tool approach)
    const processed = await enforceImageDimensions(
      imageBase64,
      orientation,
      sizePreset
    )
    const imageDataUrl = `data:${processed.mimeType};base64,${processed.base64}`

    console.log('Image generated successfully with Gemini 2.5 Flash Image')

    return NextResponse.json({
      success: true,
      imageUrl: imageDataUrl,
      prompt: imagePrompt,
    })
  } catch (error) {
    console.error('Error generating image:', error)
    return NextResponse.json(
      {
        error: 'Failed to generate image',
        details: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    )
  }
}
